"""Emails the poller sends as itself — never as, or to, an external party.

Two things live here, both sent from the one shared system identity, never
from an onboarded mailbox: a reauth prompt (the part re-onboarding itself
was missing), and the deck-built notification. Neither is a reply on a
client thread — this build's scope is solutioning's own inbox, and the
notification goes back to solutioning, not out to whoever the triggering
email came from. That's what makes `send` (not just `draft`) safe here:
nothing in this module ever addresses an external recipient.
"""

from __future__ import annotations

import base64
import email.mime.text
import os

from googleapiclient.discovery import build

from ..auth.oauth_creds import get_credentials

SERVICE_NAME = "Solutioning Agent"


def send_reauth_prompt(email_address: str) -> None:
    onboarding_url = f"{os.environ.get('SERVICE_URL', '')}/oauth/gmail/start"

    body = (
        f"{SERVICE_NAME} can no longer read your inbox — your access needs to "
        f"be renewed.\n\n"
        f"Click here to reconnect (takes 10 seconds, same as the first time):\n"
        f"{onboarding_url}\n\n"
        f"Nothing else has changed. This happens automatically about once a "
        f"week while this is still in early testing, and should stop once it "
        f"moves out of testing mode."
    )
    message = email.mime.text.MIMEText(body)
    message["to"] = email_address
    message["subject"] = f"{SERVICE_NAME}: please reconnect your inbox"
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()

    gmail = build("gmail", "v1", credentials=get_credentials())
    gmail.users().messages().send(userId="me", body={"raw": raw}).execute()


_SOURCE_LABELS = {
    "past_decks": "HT past decks",
    "web_search": "Web and social",
    "youtube": "YouTube",
    "fetch_url": "Client website",
}


def _sources_section(retrievals: list[dict]) -> str:
    """Which sources returned something and which didn't, from telemetry.

    Stating the ones that came back empty is the point, not an omission —
    a reader has to be able to tell "no prior HT work exists" apart from
    "the past-decks corpus was unreachable".
    """
    if not retrievals:
        return "  (no retrieval was recorded for this brief)"
    outcomes = {
        "success": "returned results",
        "no_results": "returned nothing",
        "error": "could not be reached",
    }
    return "\n".join(
        f"  - {_SOURCE_LABELS.get(r['source'], r['source'])}: "
        f"{outcomes.get(r['outcome'], r['outcome'])}"
        for r in retrievals
    )


def send_deck_notification(
    client_name: str | None,
    brief: str | None,
    deck_link: str | None = None,
    evidence: str | None = None,
    gaps: list[str] | None = None,
    retrievals: list[dict] | None = None,
) -> None:
    """One new email to solutioning's own notify address — never a reply
    on the triggering thread, which may have external participants.

    Carries the four things the SOW asks for in a single message: the
    brief, an evidence summary, the gaps, and the draft.
    """
    to = os.environ.get("SOLUTIONING_NOTIFY_EMAIL", "")
    if not to:
        raise RuntimeError("SOLUTIONING_NOTIFY_EMAIL is not set — nowhere to send this.")

    gap_lines = (
        "\n".join(f"  - {g}" for g in gaps)
        if gaps
        else "  (none reported)"
    )
    body = f"""A solution deck has been drafted.

CLIENT
  {client_name or '(not extracted)'}

BRIEF
  {brief or '(not extracted)'}

DRAFT DECK
  {deck_link or '(no deck link was returned)'}

EVIDENCE SUMMARY
{evidence or '  (none reported)'}

GAPS — not established, do not assume
{gap_lines}

SOURCES CHECKED
{_sources_section(retrievals or [])}

Commercials are not included: no rate, price or commercial term is
generated by the agent. This is a first draft for a person to take
forward, not a client-ready document.
"""
    message = email.mime.text.MIMEText(body)
    message["to"] = to
    message["subject"] = f"Solution deck drafted — {client_name or 'unspecified client'}"
    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()

    gmail = build("gmail", "v1", credentials=get_credentials())
    gmail.users().messages().send(userId="me", body={"raw": raw}).execute()
